source :gemcutter
gem "rails", "2.3.5"
gem "disguise", "2.0.0"
gem "ruby-openid", :require => "openid"
gem "aws-s3", :require => "aws/s3"
gem "jammit"
gem "thin"
gem "pg"
gem "hpricot", "0.8.3"
gem "closure-compiler", "1.0.0"
gem "columnize", "0.3.6"
gem "i18n", "0.6.0"
gem "json", "1.5.1"
gem 'linecache'
gem 'ruby-debug-base', "0.10.4"
gem 'ruby-debug', "0.10.4"
gem "mail", "2.4.4"
gem "polyglot"
gem "rbx-require-relative", "0.0.9"
gem "rmagick", "2.13.1"
gem "treetop", "1.4.10"
